services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: BOT_TOKEN
        value: 7551518552:AAGvaJ87gP84CtgOQyDpjUzjcy_STYvRsGw
      - key: WEBHOOK_URL
        value: https://directswap-bot.onrender.com
